version: '3.8'
services:
  analytics-engine:
    build: ./analytics-engine
    depends_on:
      - kafka

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  interaction-tracker:
    build: ./interaction-tracker
    ports:
      - "3003:3003"
    depends_on:
      - kafka

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  user-service:
    build: ./user-service
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/users
    depends_on:
      - mongo
  product-service:
    build: ./product-service
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb://mongo:27017/products
    depends_on:
      - mongo
  recommendation-service:
    build: ./recommendation-service
    ports:
      - "50051:50051"
  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - recommendation-service

volumes:
  mongo_data:
